### PR TITLE
orkney islands Blue

### PR DESCRIPTION
**Pull request by pigwin-3**
made the blue of orkney islands match closer to correct (like some have already bean doing by themselfs

remove the accidental blue bridgebetwan the flags

### CODE REVIEW

**Comment by snenyl** [comment]
Do you got images?

**Comment by pigwin-3** [comment]
ofc
Before:
before
After
after

a lil mistake on my last commit i fixed now

**Comment by pigwin-3** [comment]
I done did im so tiered I messed up åland and Orkney islands... the colors are not messed up on this version tho
flag for referanse:
image

**Review by pigwin-3 — COMMENTED** [review]
its orkney islands not åland

**Comment by snenyl** [comment]
I don't have permission to merge. It is just easier do see what has been done with images.

**Comment by ActuallyJustAVirus** [comment]
resolved with #29

**Pull request closed without merging**
