### PR TITLE
Remove blåhaj datas.json

### PR DESCRIPTION
**Pull request by vpswede98**
Removed  blåhaj, no vote from sweden to have it, cluttering

### CODE REVIEW

**Comment by MeblIkea** [comment]
> Removed  blåhaj, no vote from sweden to have it, cluttering

Yes there were twice.
The first had 54 vs 11
The second had 38 vs 7

**Comment by vpswede98** [comment]
@MeblIkea  can you link it? we're unable to find it.

**Comment by MeblIkea** [comment]
> @MeblIkea  can you link it? we're unable to find it. 
> 
https://discord.com/channels/958463934313144401/1131932662878175253/1131932662878175253
https://discord.com/channels/958463934313144401/1131691086184726649/1131691086184726649

**Comment by vpswede98** [comment]
> > @MeblIkea  can you link it? we're unable to find it.
> 
> https://discord.com/channels/958463934313144401/1131932662878175253/1131932662878175253 https://discord.com/channels/958463934313144401/1131691086184726649/1131691086184726649

Sweden did not vote for that, that where the other countries. 
Please speak with Jack or Brynte, sweden has not voted for it and wants to replaced with the kungen picture <3 
https://discord.com/channels/958463934313144401/1131988976643866654
you're the best

**Comment by MeblIkea** [comment]
> > > @MeblIkea  can you link it? we're unable to find it.
> > 
> > 
> > https://discord.com/channels/958463934313144401/1131932662878175253/1131932662878175253 https://discord.com/channels/958463934313144401/1131691086184726649/1131691086184726649
> 
> Sweden did not vote for that, that where the other countries. Please speak with Jack or Brynte, sweden has not voted for it and wants to replaced with the kungen picture <3 https://discord.com/channels/958463934313144401/1131988976643866654 you're the best

Oh I see, I'll remove it then.

**Review by MeblIkea — APPROVED** [review]
Approved.

**Pull request merged**
